#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Telephony Test Case

Specifications:
    * 13340 AT&T Requirements v5.7 Chapter 40
    * 15595 AT&T Test Plan v3.8 Section 5.1.1
"""

from __future__ import absolute_import, division

import sys
import datetime
import random
import string
from yaya import *
def get_name():
    '''
    '''
    chars = ''.join(random.sample(string.ascii_letters, 4))
    name = '%s_%s' % ('AT', chars.upper())
    return name
def vertto(flow):
    mdevice = flow.dm.GetMDevice.GetDevice
    mdevice(scrollable=True).scroll.to(text="Server")
def vertto2(flow):
    mdevice = flow.dm.GetMDevice.GetDevice
    mdevice(scrollable=True).scroll.vert.toBeginning(steps=15)
def vertto3(flow):
    mdevice = flow.dm.GetMDevice.GetDevice
    mdevice(scrollable=True).scroll.vert.toEnd(steps=15)
def vertto4(flow):
    mdevice = flow.dm.GetMDevice.GetDevice
    mdevice(scrollable=True).scroll.to(text="Phone")

contacts_call = {'descriptionContains':'Call Mobile'}
clear=[ClearBackgroundAPP(),SDevice(ClearBackgroundAPP())]

sign_to_Email=["sign_to_Email","Open Email",OpenAPP("Email"),
               "Input account",{"resourceId":"com.tct.email:id/account_email",Input:"osstabilitysend01@tcl.com"},
               "Cllick Manual",{"resourceId":"com.tct.email:id/manual_Recent"},
               "Selcect Exhange",{"text":"Exchange"},
               "Input password",{"resourceId":"com.tct.email:id/regular_password",Input:"Aa@1234567"},
               "Back",Back,
               "Click Next",{"text":"NEXT"},
               "Input username",{"resourceId":"com.tct.email:id/account_username",Input:"tct\osstabilitysend01"},
               "Input server",vertto,{"resourceId":"com.tct.email:id/account_server",Input:"mailsh.tct.tcl.com"},
               "Back",Back,
               "Next",{"text":"NEXT"},Wait(5)]

backto_contacts = NOT(FOR(4)({'text':'ALL CONTACTS', IsGone:2}, Back))

test_call_from_contacts_3G =    [   'Test Call from Contacts in 3G Network',
                                    'Launch contacts APP', OpenAPP('Contacts'),
                                    'Select first contact', {"textContains": 'AT'},
                                    'Dial contact phone', contacts_call,
                                    'Check if the MDevice is incall status', IsInCall(8),
                                    'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                                    ThreeDevice(OpenAPP('Contacts')),
                                    'Stay call connect 5s', InCallStay(5),
                                    'MDevice end call',EndCall
                                ]

test_call_from_contacts_LTE =   [   'Test Call from Contacts in LTE Network',
                                    'Launch contacts APP', OpenAPP('Contacts'),
                                    'select first contact', {"textContains": 'AT'},
                                    'Dial contact phone', contacts_call,
                                    'check if the MDevice is incall status', IsInCall(8),
                                    'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                                    'Stay call connect 5s', InCallStay(5),
                                    'MDevice end call',EndCall
                                ]

test_call_from_history_3G =     [   'Test Call from History in 3G Network',
                                    'Launch call hostory', OpenAPP('Dialer'),
                                    'Dial call', {'resourceId':'com.android.dialer:id/call_back_action'},
                                    'Check if the MDevice is incall status', IsInCall(8),
                                    'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                                    'Stay call connect 5s', InCallStay(5),
                                    'MDevice end call',EndCall
                                ]

test_call_from_history_LTE =    [   "Test Call from History in LTE Network",
                                    'Launch Dialer', OpenAPP('Dialer'),
                                    'Dial call', {'resourceId':'com.android.dialer:id/call_back_action'},
                                    'Check if the MDevice is incall status', IsInCall(8),
                                    'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                                    'Stay call connect 5s', InCallStay(5),
                                    'MDevice end call', EndCall
                                ]

test_call_receive =             [   'Test Call Receive',
                                    'Switch SDevice', SwitchSDevice,
                                    'Launch Contacts', OpenAPP('Contacts'),
                                    'select first contact', {"textContains": 'AT'},
                                    'Dial contact phone', contacts_call,
                                    'Check if the MDevice is incall status', IsInCall(8),
                                    'Switch MDevice and Answer Call', MDevice( IsRinging(10), CallAnswer, 
                                    'Stay call connect 5s', InCallStay(5) ),
                                    'MDevice end call', EndCall
                                ]

test_contacts_add =             [   'Test Contacts Add',
                                    'Launch Contacts', OpenAPP('Contacts'),
                                    backto_contacts,
                                    'Click Add contact button', {'resourceId':'com.android.contacts:id/floating_action_button'},
                                    'Select one account',{'text':'Phone-only, unsynced', IsGone:2, Click:"click"},
                                    'Input name',{'textMatches':'(Name|First name)', Input: get_name },
                                    'Input number',{'className':'android.widget.EditText', 'text':'Phone', Input: Get('common.ini', 'Telephony', 'sdevice')},
                                    'Save the contact and check if the New Contact', {'description':'Done'}
                                ]

test_contacts_remove =          [   'Test Contacts Remove',
                                    'Launch Contacts', OpenAPP('Contacts'),
                                    'Select a contact',{'textContains':'AT'},
                                    'Delect the contact',{'description':'More options'}, {'text':'Delete'}, {'text':'DELETE'}
                                ]

dual_Call=  ["Launch dailer pad",OpenAPP('Dialer'),
             "Open the dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
             'call number', CallNumber("18651502758"),
             'Check if the MDevice is incall status', IsInCall(8),
             'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
             'add other phone',{'resourceId':'com.android.dialer:id/addButton'},
             'call number', CallNumber("10010"),
             'Stay call connect 5s', InCallStay(5),
             'MDevice end call',EndCall,EndCall]

Merage_Call=["Launch dailer pad",OpenAPP('Dialer'),
             "Open the dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
             'call number',CallNumber("18651502758"),
             'Check if the MDevice is incall status', IsInCall(8),
             'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
             'add other phone',{'resourceId':'com.android.dialer:id/addButton'},
             'call number',CallNumber("10010"),
             {'resourceId':'com.android.dialer:id/holdButton',WaitTime:5},{'resourceId':'com.android.dialer:id/mergeButton'},
             'Stay call connect 5s', InCallStay(5),
             'MDevice end call',EndCall]
Test_enter_into_call=["Test_enter_into_call","Step1 Launch dailer pad",OpenAPP('Dialer'),
                      {'resourceId':'com.android.dialer:id/floating_action_button'},Home,

                      #"Step2 Launch dailer from sreen lock", Power, Wait(5), Power,
                      #"Double click the call",Point(200, 1246), Wait(1), Point(200, 1246),

                      "Step3 Launch dailer pad",OpenAPP('Dialer'),
                      "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                      'call number',CallNumber("10010"),
                      "Mdevice is in call",IsInCall(8),
                      "Stay call connect 5s", InCallStay(5),
                      'MDevice end call',
                      "Go to history",EndCall,Back,{"descriptionContains":"Call history"},
                      "Long click history",{"text":"10010",LongClick:2},
                      "Edit number before call",{"text":"Edit number before call"},

                      "step 4 call from message",OpenAPP('Messaging'),
                      "Clik add",{"resourceId":"com.android.mms:id/floating_action_button_container"},
                      "Input 10010",{"resourceId":"com.android.mms:id/recipients_editor",Input:"10010"},
                      'input any message',{"resourceId":"com.android.mms:id/embedded_text_editor",Input:"10010"},
                      "Send it",{"resourceId":"com.android.mms:id/send_button_sms",WaitTime:4},
                      "Clik meun and click call",Point(658,100),{"text":"Call"},

                      "step 5 call from browser",OpenAPP('Browser'),Wait(5),
                      "Stop the srearch",{"resourceId":"com.hawk.android.browser:id/stop",WaitTime:2},Point(307,100),
                      "Clear the http",{"resourceId":"com.hawk.android.browser:id/iv_view_url_txt_clear"},
                      "Input the HTTP",{"resourceId":"com.hawk.android.browser:id/et_view_url_search",Input:"http://meishi.meituan.com/i/poi/858011"},
                      "search",{"resourceId":"com.hawk.android.browser:id/perform_search_url",WaitTime:5},
                      "Meituan Cancel",Point(173,541),
                      "Call click",Point(658,737),
                      "Clcik the number",{"descriptionContains":"0510-88214777"},
                      "Click ok and back",{"text":"OK"},Back,Back,Back,Back,Back,

                      #"Step6 Call from Email",sign_to_Email,Recent,

                      #"Step7 Call from app","Open app",OpenAPP("MeiTuan"),
                      #"Click any shop",Point(287,699),
                      #"Chose the shop",{"test":"商家"},
                      #"contact to shop",{"resourceId":"com.sankuai.meituan.takeoutnew:id/poi_phone"},
                      #"choose the number",{"resourceId":"android:id/text1"},

                      "Step8 call from recent",OpenAPP('Dialer'),Home,ClearBackgroundAPP(),{"text":"Phone"},

                      "Step9 call from contacts",'Test Contacts Add',
                      'Launch Contacts', OpenAPP('Contacts'),
                      'Click Add contact button', {'resourceId':'com.android.contacts:id/floating_action_button'},
                      'Select one account',{'text':'Saving to'},{"text":"Phone contact"},
                      'Input name',{'textMatches':'(Name|First name)', Input: get_name },Back,
                      'Input number',{'className':'android.widget.EditText', 'text':'Phone', Input:"18651502758"},
                      'Save the contact and check if the New Contact', {'description':'Save'},clear
                    ]
Test_Speed_dialer=  ["Test_Speed_dialer","Step1",
                     "Open dailer",OpenAPP("Dialer"),
                     "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                     "Long click 2-9",
                    {"text":"1",LongClick:2},{"text":"OK"},
                    {"text":"2",LongClick:2},{"text":"CANCEL"},
                    #{"text":"3",LongClick:2},{"text":"CANCEL"},
                    {"text":"4",LongClick:2},{"text":"CANCEL"},
                    {"text":"5",LongClick:2},{"text":"CANCEL"},
                    {"text":"6",LongClick:2},{"text":"CANCEL"},
                    {"text":"7",LongClick:2},{"text":"CANCEL"},
                    {"text":"8",LongClick:2},{"text":"CANCEL"},
                    {"text":"9",LongClick:2},{"text":"CANCEL"},

                     "Step3_add manual",
                     "Long click 2",{"text":"2",LongClick:2},
                     "make sure add",{"text":"OK"},
                     "set text 2 number",{"text":"2"},
                     "Input name",{'resourceId':"com.mediatek.oplct.plugin:id/nameLable",Input:"2"},
                     "Input number",{'resourceId':"com.mediatek.oplct.plugin:id/number",Input:"10010"},
                     "Click OK",{"text":"OK"},
                     "Home",Home,
                      "Open Dialer",OpenAPP("Dialer"),
                     "Long click2",{"text":"2",LongClick:2},
                     "Calling",IsInCall(5),
                     "Stay call connect 5s", InCallStay(5),
                     'MDevice end call', EndCall,
                     "Delect",
                     {"text":"5",LongClick:2},
                     {"text":"OK"},
                     {'resourceId':"com.mediatek.oplct.plugin:id/sd_remove"},{"text":"REMOVE"},Back,

                     "Step3_add from contcats",
                     {"text":"4",LongClick:2},{"text":"OK"},
                     {"text":"4"},{'resourceId':"com.mediatek.oplct.plugin:id/contacts"},Wait(1),
                     Point(399,256),Wait(1),
                     Home,OpenAPP("Dialer"),
                     {"text":"4",LongClick:2},
                     "Mdevice is incall",IsInCall(5),
                     "Sdevice ring and answer",SDevice( IsRinging(10), CallAnswer ),
                     "Stay call connect 5s", InCallStay(5),
                     'MDevice end call', EndCall,
                     "remove the speed dialer",
                     {"text":"5",LongClick:2},{"text":"OK"},
                     {'resourceId':"com.mediatek.oplct.plugin:id/sd_remove"},
                     {"text":"REMOVE"},
                     clear
                    ]
Test_Call_from_search=["Test_Call_from_search","Open dialer",OpenAPP("Dialer"),
                       "Serarch 1",{'resourceId':"com.android.dialer:id/search_view_container",Input:1},
                       "Click the serach",SWITCH()[{"textContains":"1"}],
                       "Mdevice is incall",IsInCall(5),
                       "Stay call connect 5s", InCallStay(5),
                       'MDevice end call', EndCall,clear
                        ]
Test_press_all_the_key=["Test_press_all_the_key","Open dialer",OpenAPP("Dialer"),
                        "Open the dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                        "click all the key",
                        {"text":"1"},{"text":"2"},{"text":"3"},
                        {"text":"4"},{"text":"5"},{"text":"6"},
                        {"text":"7"},{"text":"8"},{"text":"9"},
                        {"text":"*"},{"text":"0"},{"text":"#"},
                        {"text":"0",LongClick:2},
                        "check",CheckExists(textContains="123456789*0#+"),
                        "Delect the input",{'resourceId':"com.android.dialer:id/deleteButton",LongClick:2},clear
                        ]
Test_merage_call=["Test_merage_call","Launch dailer pad",OpenAPP('Dialer'),
                  "Open dialer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                 'call number',CallNumber("18651502758"),
                 'Check if the MDevice is incall status', IsInCall(8),
                 'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                 'add other phone',"clik menu",Wait(5),Point(605,330),"Clik add call",Point(425,420),
                 "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                 'call number',CallNumber("10010"),"clik menu",Wait(5),Point(605,330),"Merage call",{"text":"Merge calls"},
                 'Stay call connect 5s', InCallStay(5),
                 'MDevice end call',EndCall,clear]
Test_hold_Merage_call= ["Test_hold_Merage_call","Launch dailer pad",OpenAPP('Dialer'),
                        "Open dialer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                       'call number',CallNumber("18651502758"),
                        'Check if the MDevice is incall status', IsInCall(8),
                        'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                        'add other phone',"clik menu",Wait(5),Point(605,330),"Clik add call",Point(425,420),
                        "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                        'call number',CallNumber("10010"),
                        "clik menu",Wait(5),Point(605,330),
                        "Merage call",{"text":"Merge calls"},Wait(5),Point(600,343),Point(426,432),
                        "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                        'call number', CallNumber("10010"),'Stay call connect 5s', InCallStay(5),
                        'MDevice end call',EndCall,EndCall,
                        "Home",clear]
Test_get_call_when_screen_lock= [  "Test_get_call_when_screen_lock","Mdevice Sleep",Power,
                                    'Switch SDevice',
                                    SDevice('Launch Contacts',OpenAPP('Contacts'),
                                    'Click Add contact button', {'resourceId':'com.android.contacts:id/floating_action_button'},
                                    'Select one account',{'text':'Saving to'},{"text":"Phone contact"},
                                    'Input name',{'textMatches':'(Name|First name)', Input: get_name },Back,
                                    'Input number',{'className':'android.widget.EditText', 'text':'Phone', Input:"18651503218"},
                                    'Save the contact and check if the New Contact', {'description':'Save'},Home,
                                    'Launch Contacts',OpenAPP('Contacts'),
                                    'select first contact', {"textContains": 'AT'},
                                    'Dial contact phone', contacts_call, 
                                    'Check if the MDevice is incall status', IsInCall(8),
                                    'Switch MDevice and Answer Call', MDevice( IsRinging(10), CallAnswer, 
                                    'Stay call connect 5s', InCallStay(5) ),
                                    'MDevice end call', EndCall,Back),clear]
Test_get_call_when_screen_unlock=[  "Test_get_call_when_screen_unlock","Mdevice Sleep",'Switch SDevice',
                                    SDevice('Launch Contacts',OpenAPP('Contacts'),
                                    'Click Add contact button', {'resourceId':'com.android.contacts:id/floating_action_button'},
                                    'Select one account',{'text':'Saving to'},{"text":"Phone contact"},
                                    'Input name',{'textMatches':'(Name|First name)', Input: get_name },Back,
                                    'Input number',{'className':'android.widget.EditText', 'text':'Phone', Input:"18651503218"},
                                    'Save the contact and check if the New Contact', {'description':'Save'},Home,
                                    'Launch Contacts',OpenAPP('Contacts'),
                                    'select first contact', {"textContains": 'AT'},
                                    'Dial contact phone', contacts_call, 
                                    'Check if the MDevice is incall status', IsInCall(8),
                                    'Switch MDevice and Answer Call', MDevice( IsRinging(10), CallAnswer, 
                                    'Stay call connect 5s', InCallStay(5) ),
                                    'MDevice end call', EndCall,Back),clear]
Test_reply_Call_from_notification=["Test_reply_Call_from_notification","Mdevice open notification",OpenNotification,
                                   "Mdevice clear all",SWITCH()[{"text":"CLEAR ALL"}],
                                   "SDevice launch diler",SDevice(
                                   "Open dialer",OpenAPP("Dialer"),SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                                   "call number",CallNumber("18651503218"),IsInCall(8),
                                   "MDevice is ringing",MDevice(IsRinging(10)),
                                   "Sdevice end call",EndCall),
                                   "Mdevice open notification",OpenNotification,
                                   "Mdevice call back",{"text":"CALL BACK"},
                                   'Check if the MDevice is incall status', IsInCall(8),
                                   'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                                   'Stay call connect 5s and end call', InCallStay(5),EndCall,
                                    clear
                                   ]
Test_reply_Call_from_lockscreen=[  "Test_reply_Call_from_lockscreen","Mdevice lock screen",Power,
                                   "SDevice launch diler",SDevice(
                                   "Open dialer",OpenAPP("Dialer"),SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                                   "call number",CallNumber("18651503218"),IsInCall(8),
                                   "MDevice is ringing",MDevice(IsRinging(10)),
                                   "Sdevice end call",EndCall),
                                   "Click missed call",{"text":"Missed call",DoubleClick:"12312"},Wait(1),
                                   "Click call",Point(655,422),Wait(1),
                                   'Check if the MDevice is incall status', IsInCall(8),
                                   'Switch SDevice and Answer Call', SDevice(IsRinging(10),CallAnswer),
                                   'Stay call connect 5s and end call', InCallStay(5),EndCall,
                                   "Mdevice sleep",Power,Wait(2),
                                   "Mdevice Power on",Power,
                                   "Check",{'text':"Missed call",IsGone:1},
                                   "Unlock screen",{'resourceId':"com.android.systemui:id/notification_stack_scroller",Swipe:"up"},
                                    clear
                                   ]
Test_call_mute_function=["Test_call_mute_function","Launch dailer pad",OpenAPP('Dialer'),
                         "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                        'call number',CallNumber("18651502758"),
                        'Check if the MDevice is incall status', IsInCall(8),
                        'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),Point(242,348),Wait(5),Point(242,348),
                         'Stay call connect 5s', InCallStay(5),
                        'MDevice end call',EndCall,Back,clear
                         ]
Test_call_recording_function=["Test_call_recording_function","Launch dailer pad",OpenAPP('Dialer'),SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                            'call number',CallNumber("18651502758"),
                            'Check if the MDevice is incall status', IsInCall(8),
                            'Switch SDevice and Answer Call', SDevice( IsRinging(10), CallAnswer ),
                            "clik menu",Wait(5),Point(605,330),"Clik add call",Point(538,525),"Delay 5s",Wait(5),Point(605,330),Point(538,525),
                            'Stay call connect 5s', InCallStay(5),'MDevice end call',EndCall,Back,
                            "Open filemanger",OpenAPP("Filemanager"),{"text":"Recents"},Point(410,244),"Play the record",Wait(5),Back,
                            "Delect the record",Point(650,220),{"text":"Delete"},{"text":"DELETE"},Back,Back,Back,clear
                              ]
Test_Call_before_edit=["Test_Call_before_edit",OpenAPP('Dialer'),SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                       'call number',CallNumber("10010"),IsInCall(8),
                       "Stay call connect 5s", InCallStay(5),
                       'MDevice end call',EndCall,Wait(1),Back,
                       "Go to history",{"descriptionContains":"Call history"},
                       "Longclick",{"resourceId":"com.android.dialer:id/primary_action_view",LongClick:2},
                       "Click text",{"text":"Edit number before call"},
                       "Delect the number",{"resourceId":"com.android.dialer:id/deleteButton",LongClick:2},
                       "Input new number",{"resourceId":"com.android.dialer:id/digits",Input:"18651502758"},
                       "Send",{"resourceId":"com.android.dialer:id/dialpad_floating_action_button"},
                       'Check if the MDevice is incall status', IsInCall(8),
                       'Switch SDevice and Answer Call', SDevice(IsRinging(10), CallAnswer),
                       'Stay call connect 5s', InCallStay(5),
                       'MDevice end call', EndCall,
                       "Click meun",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                       "selct history",{"text":"Call history"},
                       "Long click any view",{"resourceId":"com.android.dialer:id/primary_action_view",LongClick:2},
                       "Click edit number",{"text":"Edit number before call"},
                       "Delect",
                       {"resourceId":"com.android.dialer:id/deleteButton",LongClick:2},
                       {"resourceId":"com.android.dialer:id/deleteButton",LongClick:2},
                       "Input new number",{"resourceId":"com.android.dialer:id/digits",Input:"10010"},
                       {"resourceId":"com.android.dialer:id/dialpad_floating_action_button"}, IsInCall(8),InCallStay(5),EndCall,
                       Back,Back,Back,clear]
Test_enterinto_FND =["Test_enterinto_FND","Launch dailer pad",OpenAPP('Dialer'),
                     "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                     "Open call settings",{"text": "Settings"},
                     "Open Calls",{"text": "Calls"},
                     "Open FND",{"text": "Fixed dialing numbers"},
                     "Open FDN list",{"text": "FDN list"},
                     "Check",CheckExists(textContains="No contacts on your SIM card."),
                     "Back",Back,Back,Back,Back,clear]
Test_add_FND_from_contacts=["Test_add_FND_from_contacts","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open FND",{"text": "Fixed dialing numbers"},
                            "Open FDN list",{"text": "FDN list"},
                            "Open the Meun",Point(655,105),
                            "Add FDN",{"text":"Add contact"},
                            "Open the Meun",Point(655,105),
                            "Imprort from Contacts",{"text":"Import from Contacts"},Wait(1),
                            "Select contact",{"text":"Contacts"},Wait(1),
                            "Select FDN",Point(382,254),Wait(1),
                            "Save",{"text":"SAVE"},
                            "Input PIN2",{"resourceId":"com.android.phone:id/pin",Input:"123456"},
                            "Click ok",{"text":"OK"},
                            "Check",CheckExists(resourceId="android:id/text1"),
                            "delect FND",{"resourceId":"android:id/text1"},
                            "Select Delect",{"text":"Delete contact"},
                            "Input PIN2",{"resourceId":"com.android.phone:id/pin",Input:"123456"},
                            "Click ok",{"text":"OK"},
                            "Back",Back,Back,Back,Back,Back,clear
                            ]
Test_check_Call_wait_status= ["Test_check_Call_wait_status","Launch dailer pad",OpenAPP('Dialer'),
                              "Open dailer",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                              "Input *#43#",{"resourceId":"com.android.dialer:id/digits",Input:"*#43#"},
                              "Send",{"resourceId":"com.android.dialer:id/dialpad_floating_action_button"},Wait(1),
                              "Press Ok",{"text":"OK"},
                              "Check",CheckExists(textContains="ADD A FAVORITE"),clear
                              ]
Test_open_Call_wait=        ["Test_open_Call_wait","Launch dailer pad",OpenAPP('Dialer'),
                              "Open dailer",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                              "Input *43#",{"resourceId":"com.android.dialer:id/digits",Input:"*43#"},
                              "Send",{"resourceId":"com.android.dialer:id/dialpad_floating_action_button"},Wait(1),
                              "Check",CheckExists(textContains="Service enabled"),
                              "Press Ok",{"text":"OK"},
                              "Check",CheckExists(textContains="ADD A FAVORITE"),clear
                              ]
Test_close_Call_wait=        ["Test_close_Call_wait","Launch dailer pad",OpenAPP('Dialer'),
                              "Open dailer",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                              "Input #43#",{"resourceId":"com.android.dialer:id/digits",Input:"#43#"},
                              "Send",{"resourceId":"com.android.dialer:id/dialpad_floating_action_button"},Wait(1),
                             "Check", CheckExists(textContains="Service disabled"),
                              "Press Ok",{"text":"OK"},
                              "Check",CheckExists(textContains="ADD A FAVORITE"),clear
                              ]
Test_get_call_when_send_recerive_message=["Test_get_call_when_send_recerive_message","Open message",OpenAPP('Messaging'),
                                          "Clik add",{"resourceId":"com.android.mms:id/floating_action_button_container"},
                                          "Input self",{"resourceId":"com.android.mms:id/recipients_editor",Input:"18651503218"},
                                          'input any message',{"resourceId": "com.android.mms:id/embedded_text_editor", Input: "10010"},
                                          "Send it", {"resourceId": "com.android.mms:id/send_button_sms"},
                                          "Back",Back,Back,Back,
                                          "Switch SDevice",SDevice(
                                          'Launch Contacts',OpenAPP('Contacts'),Wait(3),
                                          'select first contact', {"textContains": 'AT'},
                                          'Dial contact phone', contacts_call,
                                          'Check if the MDevice is incall status', IsInCall(8),
                                          'Switch MDevice and Answer Call', MDevice( IsRinging(10), CallAnswer),
                                          'Stay call connect 5s', InCallStay(5),EndCall,Back),
                                          #"Close",{"text":"CLOSE"},
                                          clear]
Test_Calling_over_15 =["Test_Calling_over_15","Launch dailer pad",OpenAPP('Dialer'),
                       "Make a call",CallNumber("18651502758"),
                       "SDevice ring and answer",SDevice(IsRinging(10), CallAnswer),
                       'Stay call connect 900s', InCallStay(90),
                       'MDevice end call', EndCall,clear
                       ]
Test_Call_1_send  =["Test_Call_1_send","Launch dailer pad",OpenAPP('Dialer'),
                    "Make a call",CallNumber("18651502758"),
                    'Check if the MDevice is incall status', IsInCall(8),
                    "SDevice ring and answer",SDevice(IsRinging(10), CallAnswer),
                    'add other phone',Wait(5),Point(605,330),
                    "Clik add call",Wait(5),Point(421,428),
                    "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                    'call number',CallNumber("18651503938"),
                    "ThreeDevice ring and answer",ThreeDevice(IsRinging(10), CallAnswer),
                    "clik menu",Wait(5),Point(605,330),
                    "Merage call",{"text":"Merge calls"},
                    "SDdevice lunch diler",SDevice(OpenAPP('Dialer'),
                    #"Click add call",{"text":"Add call"},
                    "Timedelay",Wait(5),
                    "Input1",CallNumber("1")),
                    'Stay call connect 5s', InCallStay(5),
                    "Medvice End Call",EndCall,
                    "Back",Back,clear]
Test_Call_2_send =["Test_Call_2_send","Launch dailer pad",OpenAPP('Dialer'),
                    "Make a call",CallNumber("18651502758"),
                    'Check if the MDevice is incall status', IsInCall(8),
                    "SDevice ring and answer",SDevice(IsRinging(10), CallAnswer),
                    'add other phone',Wait(5),Point(605,330),
                    "Clik add call",Wait(5),Point(421,428),
                    "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                    'call number',CallNumber("18651503938"),
                    "ThreeDevice ring and answer",ThreeDevice(IsRinging(10), CallAnswer),
                    "clik menu",Wait(5),Point(605,330),
                    "Merage call",{"text":"Merge calls"},
                    'add third phone',Wait(5),Point(605,330),
                    "Clik add call",Wait(5),Point(421,428),
                    "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                    'call number',CallNumber("10010"),
                   "Timedelay",Wait(5),
                    "Home",Home,
                   "Launch dailer pad",OpenAPP('Dialer'),
                   #"Click add call",{"text":"Add call"},
                    "Timedelay",Wait(1),
                    "Input1",CallNumber("2"),
                   "Call stay 5s",InCallStay(5),
                   "call end",EndCall,EndCall,clear]
Test_Call_3_send=["Test_Call_3_send","Launch dailer pad",OpenAPP('Dialer'),
                    "Make a call",CallNumber("18651502758"),
                    'Check if the MDevice is incall status', IsInCall(8),
                    "SDevice ring and answer",SDevice(IsRinging(10), CallAnswer),
                    'add other phone',Wait(5),Point(605,330),
                    "Clik add call",Wait(5),Point(421,428),
                    "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                    'call number',CallNumber("18651503938"),
                    "ThreeDevice ring and answer",ThreeDevice(IsRinging(10), CallAnswer),
                    "clik menu",Wait(5),Point(605,330),
                    "Merage call",{"text":"Merge calls"},
                    'add third phone',Wait(5),Point(605,330),
                    "Clik add call",Wait(5),Point(421,428),
                    "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                    'call number',CallNumber("10010"),
                   "Timedelay",Wait(5),
                    "Home",Home,
                   "Launch dailer pad",OpenAPP('Dialer'),
                   #"Click add call",{"text":"Add call"},
                    "Timedelay",Wait(1),
                    "Input3 and wait",CallNumber("3"),Wait(5),
                    "Back",Back,
                    'OpenNotification',OpenNotification,Wait(1),
                    "Ponit Call",Point(280,235),
                    "Call stay 5s",InCallStay(5),
                    "call end",EndCall,clear]
Test_Call_2x_send=["Test_Call_2x_send","Launch dailer pad",OpenAPP('Dialer'),
                    "Make a call",CallNumber("18651502758"),
                    'Check if the MDevice is incall status', IsInCall(8),
                    "SDevice ring and answer",SDevice(IsRinging(10), CallAnswer),
                    'add other phone',Wait(5),Point(605,330),
                    "Clik add call",Wait(5),Point(421,428),
                    "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                    'call number',CallNumber("18651503938"),
                    "ThreeDevice ring and answer",ThreeDevice(IsRinging(10), CallAnswer),
                    "clik menu",Wait(5),Point(605,330),
                    "Merage call",{"text":"Merge calls"},
                    'add third phone',Wait(5),Point(605,330),
                    "Clik add call",Wait(5),Point(421,428),
                    "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                    'call number',CallNumber("10010"),
                    "Timedelay",Wait(5),
                    "Home",Home,
                    "Launch dailer pad",OpenAPP('Dialer'),
                   #"Click add call",{"text":"Add call"},
                    "Timedelay",Wait(1),
                    "Input3 and wait",CallNumber("3"),Wait(5),
                    "Input2x and wait",CallNumber("21"),Wait(2),
                    "Call stay 5s",InCallStay(5),
                    "call end", EndCall,EndCall,clear]
Test_check_the_call_forward=["Test_check_the_call_forward","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "check",CheckExists(textContains="Always forward"),
                            "check",CheckExists(textContains="When busy"),
                            "check",CheckExists(textContains="When unanswered"),
                            "check",CheckExists(textContains="When unreachable"),
                             clear
                             ]
Test_Turn_on_Call_forward=["Test_Turn_on_Call_forward","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "Always forward",{"text":"Always forward"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding all calls to"),
                            "Turn off Always forward",{"text":"Always forward"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "When busy",{"text":"When busy"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "Turn off when busy forward",{"text":"When busy"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "When unanswered",{"text":"When unanswered"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update", SWITCH()[{"text": "TURN ON"}][{"text": "UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "Turn off When unanswered",{"text":"When unanswered"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "Turn off When unreachable",{"text":"When unreachable"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "Back",Back,Back,Back,Back,clear]
Test_Call_forward_Cancel=["Test_Call_forward_Cancel","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "Always forward",{"text":"Always forward"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding all calls to"),
                            "CANCEL Always forward", {"text": "Always forward"}, {"text": "CANCEL"},
                            "check", CheckExists(textContains="Forwarding all calls to"),
                            "Turn off Always forward",{"text":"Always forward"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "When busy",{"text":"When busy"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "CANCEL When busy", {"text": "When busy"}, {"text": "CANCEL"},
                            "check", CheckExists(textContains="Forwarding to"),
                            "Turn off when busy forward",{"text":"When busy"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "When unanswered",{"text":"When unanswered"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update", SWITCH()[{"text": "TURN ON"}][{"text": "UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "CANCEL When unanswered", {"text": "When unanswered"}, {"text": "CANCEL"},
                            "check", CheckExists(textContains="Forwarding to"),
                            "Turn off When unanswered",{"text":"When unanswered"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "CANCEL When unreachable", {"text": "When unreachable"}, {"text": "CANCEL"},
                            "check", CheckExists(textContains="Forwarding to"),
                            "Turn off When unreachable",{"text":"When unreachable"},{"text":"TURN OFF"},
                            "Wait", Wait(4),

                            "Any type input",
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"10010"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "Error make sure",{"text":"OK"},
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"112"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "Error make sure",{"text":"OK"},
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:",,,###%%%@@"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "Error make sure",{"text":"OK"},
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"9999999999999999999999999"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "Error make sure",{"text":"OK"},
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"00"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "Error make sure",{"text":"OK"},
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:" "},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "Error make sure",{"text":"OK"},
                            "Back",Back,Back,Back,Back,clear]
Test_Turnonoff_always_forward=["Test_Turnonoff_always_forward","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "Always forward",{"text":"Always forward"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding all calls to"),
                            "Turn off Always forward",{"text":"Always forward"},{"text":"TURN OFF"},
                            "Wait",Wait(4),
                            "Click Always forward again",{"text":"Always forward"},
                            "Check turn off",CheckExists(textContains="TURN ON"),
                            Back,Back,Back,Back,Back,Back,clear]
Test_Turnonoff_when_busy=["Test_Turnonoff_when_busy","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "When busy", {"text": "When busy"},
                            "Input the number", {"resourceId": "android:id/edit", Input: "18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check", CheckExists(textContains="Forwarding to"),
                            "Turn off when busy forward", {"text": "When busy"}, {"text": "TURN OFF"},
                            "Wait", Wait(4),
                            "Click When busy again", {"text": "When busy"},
                            "Check turn off", CheckExists(textContains="TURN ON"),
                             Back, Back, Back, Back, Back, Back,clear
                          ]
Test_Turnonoff_when_unanswered=["Test_Turnonoff_when_unanswered","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "When unanswered", {"text": "When unanswered"},
                            "Input the number", {"resourceId": "android:id/edit", Input: "18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check", CheckExists(textContains="Forwarding to"),
                            "Turn off when busy forward", {"text": "When unanswered"}, {"text": "TURN OFF"},
                            "Wait", Wait(4),
                            "Click When unanswered again", {"text": "When unanswered"},
                            "Check turn off", CheckExists(textContains="TURN ON"),
                             Back, Back, Back, Back, Back, Back,clear]
Test_Turnonoff_unreachable=["Test_Turnonoff_unreachable","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "When unreachable", {"text": "When unreachable"},
                            "Input the number", {"resourceId": "android:id/edit", Input: "18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check", CheckExists(textContains="Forwarding to"),
                            "Turn off When unreachable forward", {"text": "When unreachable"}, {"text": "TURN OFF"},
                            "Wait", Wait(4),
                            "Click When unreachable again", {"text": "When unreachable"},
                            "Check turn off", CheckExists(textContains="TURN ON"),
                             Back, Back, Back, Back, Back, Back, clear]
Test_Alawys_forward=         ["Test_Alawys_forward","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "Always forward",{"text":"Always forward"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding all calls to"),
                            "Switch Sdevice",SDevice(
                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Make a call to Mdevice",CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device",ThreeDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call",SDevice( InCallStay(5),EndCall),
                            "Home",Home,

                            "Close call wait",Test_close_Call_wait,
                            "Make a call",CallNumber("10010"), IsInCall(10),
                            "Switch Sdevice",SDevice(
                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Make a call to Mdevice",CallNumber("1865118651502758503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device",ThreeDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call",SDevice( InCallStay(5),EndCall),
                            "Mdevice End call",EndCall,

                            "Open call wait", Test_open_Call_wait,
                            "Make a call", CallNumber("10010"),IsInCall(10),
                            "add other phone",Wait(5),Point(605,330),
                            "Clik add call",Wait(5),Point(421,428),
                            "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                            'call number',CallNumber("10010"),
                            "Wait",Wait(5),
                            "Switch Sdevice", SDevice(
                            "Launch dailer pad", OpenAPP('Dialer'),
                            "Make a call to Mdevice", CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device", ThreeDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call", SDevice(InCallStay(5), EndCall),
                            "Mdevice End call and back", EndCall,Wait(1),EndCall,Wait(1),Back,Back,

                            "Test arlplane mode",
                            "Open quciksettings",OpenQuickSettings,
                            "Open airplane",{"descriptionContains":"Airplane mode"},
                            "Switch Sdevice", SDevice(
                            "Launch dailer pad", OpenAPP('Dialer'),
                            "Make a call to Mdevice", CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device", ThreeDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call", SDevice(InCallStay(5), EndCall),
                            "Close airplane",{"descriptionContains":"Airplane mode"},
                            "Wait",Wait(6),
                            "Home",Home,

                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "Turn off Always forward",{"text":"Always forward"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "Home",Home,clear
                             ]
Test_when_busy=             ["Test_when_busy","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "When busy",{"text":"When busy"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "Switch Sdevice",SDevice(
                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Make a call to Mdevice",CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device",MDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call",SDevice( InCallStay(5),EndCall),
                            "Home",Home,

                            "Close call wait",Test_close_Call_wait,
                            "Make a call",CallNumber("10010"), IsInCall(10),
                            "Switch Sdevice",SDevice(
                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Make a call to Mdevice",CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device",ThreeDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call",SDevice( InCallStay(5),EndCall),
                            "Mdevice End call",EndCall,

                            "Open call wait", Test_open_Call_wait,
                            "Make a call", CallNumber("10010"),IsInCall(10),
                            "add other phone",Wait(5),Point(605,330),
                            "Clik add call",Wait(5),Point(421,428),
                            "Open dailer pad",SWITCH()[{'resourceId':'com.android.dialer:id/floating_action_button'}],
                            'call number',CallNumber("10010"),
                            "Wait",Wait(5),
                            "Switch Sdevice", SDevice(
                            "Launch dailer pad", OpenAPP('Dialer'),
                            "Make a call to Mdevice", CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device", MDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call", SDevice(InCallStay(5), EndCall),
                            "Mdevice End call and back", EndCall,Wait(1),EndCall,Wait(1),Back,Back,

                             "End call directly",
                             "Switch Sdevice",SDevice(
                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Make a call to Mdevice",CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Mdevice option",MDevice(IsRinging(10), EndCall),
                            "Three device",ThreeDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call",SDevice( InCallStay(5),EndCall),


                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "Turn off When busy",{"text":"When busy"},{"text":"TURN OFF"},
                            "Wait", Wait(4),
                            "Home",Home,clear
                             ]
Test_when_unanswered=       ["Test_when_unanswered","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "When unanswered",{"text":"When unanswered"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "Switch Sdevice",SDevice(
                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Make a call to Mdevice",CallNumber("18651503218")),
                            "Three device", ThreeDevice(IsRinging(30), CallAnswer),
                            "SDevice stay 5s and end call",SDevice( InCallStay(5),EndCall),
                            "Turn off When unanswered", {"text": "When unanswered"}, {"text": "TURN OFF"},
                            "Wait", Wait(4),
                            "Home", Home,clear
                             ]
Test_when_unreachable=      ["Test_when_unreachable","Launch dailer pad",OpenAPP('Dialer'),
                            "Open the Menu",{"resourceId":"com.android.dialer:id/dialtacts_options_menu_button"},
                            "Open call settings",{"text": "Settings"},
                            "Open Calls",{"text": "Calls"},
                            "Open Call Forward",{"text": "Call forwarding"},
                            "Wait",Wait(3),
                            "When unreachable",{"text":"When unreachable"},
                            "Input the number",{"resourceId":"android:id/edit",Input:"18651503938"},
                            "Turn on or update",SWITCH()[{"text":"TURN ON"}][{"text":"UPDATE"}],
                            "Wait", Wait(4),
                            "check",CheckExists(textContains="Forwarding to"),
                            "Test arlplane mode",
                            "Open quciksettings", OpenQuickSettings,
                            "Open airplane", {"descriptionContains": "Airplane mode"},
                            "Switch Sdevice",SDevice(
                            "Launch dailer pad",OpenAPP('Dialer'),
                            "Make a call to Mdevice",CallNumber("18651503218"),
                            'Check if the SDevice is incall status', IsInCall(10)),
                            "Three device",ThreeDevice(IsRinging(10), CallAnswer),
                            "SDevice stay 5s and end call",SDevice( InCallStay(5),EndCall),
                            "Close airplane",{"descriptionContains":"Airplane mode"},
                            "Back",Back,Wait(1),Back,
                            "Open Call Forward", {"text": "Call forwarding"},
                            "Wait", Wait(3),
                            "Turn off When unreachable", {"text": "When unreachable"}, {"text": "TURN OFF"},
                            "Wait",Wait(6),
                            "Home",Home,clear
                             ]
Test_add_call_tomian=["Test_add_call_tomian","Mdevice Back",Back,
                      "Click app",{"descriptionContains":"Apps"},
                      "vert to call",vertto4,
                      "Long click call",{"text":"Phone",Drag:(500,500)},
                      "Check Phone",CheckExists(textContains="Phone",instance=1),
                       clear
                      ]
Test_scroll_history_contacts_quick_dialer=["Test_scroll_history_contacts_quick_dialer","Launch dailer pad",OpenAPP('Dialer'),Wait(2),
                                           "History",
                                            "Go to history",{"descriptionContains":"Call history"},
                                            "Scroll the history",vertto3,vertto2,
                                           "Open dailer pad",SWITCH()[{'resourceId': 'com.android.dialer:id/floating_action_button'}],
                                           "Speed dial",
                                           "Long click 9",{"text":"9",LongClick:2},
                                           "Click OK",{"text":"OK"},
                                           "Scroll the speed dial", vertto3, vertto2,Back,Back,
                                           "Go to contacts",Point(610, 200),
                                           "Scroll the contacts", vertto3, vertto2,
                                           clear
]

def setup(flow):
    pass

def teardown(flow):
    pass

#######################
# 
#######################
case_list = [
        #('Contacts3G', 20, 2, test_call_from_contacts_3G, MDevice(EndCall, backto_contacts))#,
        #('Contacts3GLTE', 60, 2, test_call_from_contacts_LTE, MDevice(EndCall, backto_contacts)),
        #('History3G', 20, 2, test_call_from_history_3G, MDevice(EndCall, backto_contacts)),
        #('History3GLTE',60, 2, test_call_from_history_LTE , MDevice(EndCall, backto_contacts)),
        #('CallReceive', 100, 2,test_call_receive, SDevice(EndCall, backto_contacts)),
        #('ContactsAdd', 20, 2, test_contacts_add, MDevice(EndCall, backto_contacts))#,
        #('ContactsDel', 20, 2, test_contacts_remove, MDevice(EndCall, backto_contacts)),
        #('Dual call',20,2,dual_Call,None),
        #("Merage call",20,2,Merage_Call,None),
        #("Different ways Enter into call",20,1,Test_enter_into_call,MDevice(Home)),
        #("Speed Dailer",20,2,Test_Speed_dialer,clear),
        ("Call from search",20,3,Test_Call_from_search,clear),
        #("Press all the key in the Dailer",20,1,Test_press_all_the_key,clear),
        #("Merage call",20,1,Test_merage_call,clear),
        #("Hold the Merage Call",20,1,Test_hold_Merage_call,clear),
        #("Get call when screen lock",20,1,Test_get_call_when_screen_lock,clear),
        #("Get call when screen lock",20,1,Test_get_call_when_screen_unlock,clear),
        #("Replay call from Notification",20,1,Test_reply_Call_from_notification,clear),
        #("Replay call from Notification", 20, 1, Test_reply_Call_from_lockscreen, clear),
        #("Click mute button",20,1,Test_call_mute_function,clear),
        #("Call recording",20,1,Test_call_recording_function,clear),
        #("Call before edit",20,1,Test_Call_before_edit,clear),
        #("Enter into FDN",20,1,Test_enterinto_FND,clear),
        #("Add contacts into FND",20,1,Test_add_FND_from_contacts,clear),
        #("Input *#43#",20,1,Test_check_Call_wait_status,clear),
        #("Input *43#",20,1,Test_open_Call_wait,clear),
        #("Input #43#",20,1,Test_close_Call_wait,clear),
        #("Incoming call when Get/sent message",20,1,Test_get_call_when_send_recerive_message,clear),
        #("Call long time",20,1,Test_Calling_over_15,clear),
        #("MMI 1+send",20,1,Test_Call_1_send,clear),
        #("MMI 2+send",20,1,Test_Call_2_send,clear),
        #("MMI 3+send",20,1,Test_Call_3_send,clear),
        #("MMI 2x+send",20,1,Test_Call_2x_send,clear),
        #("Check the call forwarding option",20,1,Test_check_the_call_forward,clear),
        #("Callforward",20,1,Test_Turn_on_Call_forward,clear),
        #("Callforward",20,1,Test_Call_forward_Cancel,clear),
        #("Callforward",20,1,Test_Turnonoff_always_forward,clear),
        #("Callforward",20,1,Test_Turnonoff_when_busy,clear),
        #("Callforward",20,1,Test_Turnonoff_when_unanswered,clear),
        #("Callforward",20,1,Test_Turnonoff_unreachable,clear),
        #("Always forward",20,1,Test_Alawys_forward,clear),
        #("When busy",20,1,Test_when_busy,clear),
        #("When unanswered",20,1,Test_when_unanswered,clear),
        #("When unreachable",20,1,Test_when_unreachable,clear),
        #("Add call to main screen",20,1,Test_add_call_tomian,clear),
        #("Scorll the list",20,1,Test_scroll_history_contacts_quick_dialer,clear)
     ]
case_list1=[ ("Replay call from Notification", 20, 1, Test_reply_Call_from_lockscreen, clear)]
module_total_time = sum([item[1] for item in case_list])
module_mini_total_time = sum([item[2] for item in case_list])

run_list = StabilityTestTemplate(case_list,setup, teardown)

if __name__ == '__main__':
    import run
    run.main(modu='Telephony')
